catalog:
  version: "1.0"
  categories:
    core:
      name: "Core Infrastructure"
      description: "Essential system services"
      services:
        - nginx-proxy-manager
        - authelia
        - redis
        - fail2ban
        - portainer

    media:
      name: "Media Services"
      description: "Media management and streaming"
      services:
        - plex
        - sonarr
        - radarr
        - lidarr
        - bazarr

    downloads:
      name: "Download Management"
      description: "Download clients and indexers"
      services:
        - qbittorrent
        - prowlarr
        - nzbget

    books:
      name: "Book Services"
      description: "Book and audiobook management"
      services:
        - readarr
        - calibre
        - audiobookshelf
        - lazylibrarian

    monitoring:
      name: "Monitoring Services"
      description: "System monitoring and metrics"
      services:
        - prometheus
        - grafana
        - tautulli
        - watchtower

    interface:
      name: "User Interface"
      description: "User-facing dashboards"
      services:
        - organizr
        - overseerr
        - watchlist

    remote:
      name: "Remote Access"
      description: "Secure remote desktop access"
      services:
        - novnc
        - vnc

    utility:
      name: "Utility Services"
      description: "Additional utility and automation tools"
      services:
        - recyclarr
        - unpackerr

  services:
    nginx-proxy-manager:
      name: "Nginx Proxy Manager"
      description: "Reverse proxy and SSL management"
      image: "jc21/nginx-proxy-manager:latest"
      required: true
      resources:
        cpu: 1
        memory: 512
      ports:
        - "80:80"
        - "81:81"
        - "443:443"
      volumes:
        - ./nginx-proxy-manager/data:/data
        - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

    authelia:
      name: "Authelia"
      description: "Two-factor authentication and SSO"
      image: "authelia/authelia:latest"
      required: true
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./authelia:/config
      depends_on:
        - redis

    redis:
      name: "Redis"
      description: "Session management for Authelia"
      image: "redis:latest"
      required: true
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./redis:/data

    fail2ban:
      name: "Fail2Ban"
      description: "Intrusion prevention system"
      image: "crazymax/fail2ban:latest"
      required: true
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./fail2ban/data:/data
        - ./logs:/var/log:ro

    portainer:
      name: "Portainer"
      description: "Docker management interface"
      image: "portainer/portainer-ce:latest"
      required: true
      resources:
        cpu: 1
        memory: 256
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./portainer/data:/data
      depends_on:
        - nginx-proxy-manager
        - authelia
      security_opt:
        - no-new-privileges:true

    plex:
      name: "Plex Media Server"
      description: "Media streaming server"
      image: "lscr.io/linuxserver/plex:latest"
      resources:
        cpu: 2
        memory: 2048
      network_mode: "host"
      volumes:
        - ./plex/config:/config
        - ./media:/media

    sonarr:
      name: "Sonarr"
      description: "TV series management"
      image: "lscr.io/linuxserver/sonarr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./sonarr/config:/config
        - ./media/tv:/tv
        - ./downloads:/downloads
      depends_on:
        - qbittorrent
        - prowlarr

    radarr:
      name: "Radarr"
      description: "Movie management"
      image: "lscr.io/linuxserver/radarr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./radarr/config:/config
        - ./media/movies:/movies
        - ./downloads:/downloads
      depends_on:
        - qbittorrent
        - prowlarr

    lidarr:
      name: "Lidarr"
      description: "Music management"
      image: "lscr.io/linuxserver/lidarr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./lidarr/config:/config
        - ./media/music:/music
        - ./downloads:/downloads
      depends_on:
        - qbittorrent
        - prowlarr

    bazarr:
      name: "Bazarr"
      description: "Subtitle management"
      image: "lscr.io/linuxserver/bazarr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./bazarr/config:/config
        - ./media:/media
      depends_on:
        - sonarr
        - radarr

    qbittorrent:
      name: "qBittorrent"
      description: "Torrent client"
      image: "ghcr.io/hotio/qbittorrent:latest"
      resources:
        cpu: 1
        memory: 512
      ports:
        - "8080:8080"
      volumes:
        - ./qbittorrent/config:/config
        - ./downloads:/downloads

    prowlarr:
      name: "Prowlarr"
      description: "Indexer manager"
      image: "lscr.io/linuxserver/prowlarr:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./prowlarr/config:/config
      depends_on:
        - qbittorrent

    nzbget:
      name: "NZBGet"
      description: "Usenet downloader"
      image: "lscr.io/linuxserver/nzbget:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./nzbget/config:/config
        - ./downloads:/downloads

    readarr:
      name: "Readarr"
      description: "Book management"
      image: "lscr.io/linuxserver/readarr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./readarr/config:/config
        - ./media/books:/books
        - ./downloads:/downloads
      depends_on:
        - qbittorrent

    calibre:
      name: "Calibre"
      description: "Full-featured ebook management system and server"
      image: "lscr.io/linuxserver/calibre:latest"
      resources:
        cpu: 1
        memory: 1024
      volumes:
        - ./calibre/config:/config
        - ./media/books:/books

    audiobookshelf:
      name: "Audiobookshelf"
      description: "Audiobook and podcast server"
      image: "ghcr.io/advplyr/audiobookshelf:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./audiobookshelf/config:/config
        - ./media/audiobooks:/audiobooks

    lazylibrarian:
      name: "LazyLibrarian"
      description: "Book download automation"
      image: "lscr.io/linuxserver/lazylibrarian:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./lazylibrarian/config:/config
        - ./media/books:/books
        - ./downloads:/downloads
      depends_on:
        - qbittorrent

    prometheus:
      name: "Prometheus"
      description: "Metrics collection"
      image: "prom/prometheus:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus_data:/prometheus

    grafana:
      name: "Grafana"
      description: "Metrics visualization"
      image: "grafana/grafana:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./grafana:/var/lib/grafana
      depends_on:
        - prometheus

    tautulli:
      name: "Tautulli"
      description: "Plex statistics and monitoring"
      image: "lscr.io/linuxserver/tautulli:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./tautulli/config:/config
      depends_on:
        - plex

    watchtower:
      name: "Watchtower"
      description: "Automatic container updates"
      image: "containrrr/watchtower:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    organizr:
      name: "Organizr"
      description: "Services dashboard"
      image: "organizr/organizr:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./organizr/config:/config

    overseerr:
      name: "Overseerr"
      description: "Media request management"
      image: "lscr.io/linuxserver/overseerr:latest"
      resources:
        cpu: 1
        memory: 512
      volumes:
        - ./overseerr/config:/config
      depends_on:
        - plex

    watchlist:
      name: "Watchlist"
      description: "Media watchlist management"
      image: "ghcr.io/linuxserver/watchlist:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./watchlist/config:/config

    novnc:
      name: "noVNC"
      description: "Web-based VNC client with secure proxy"
      image: "ghcr.io/linuxserver/novnc:latest"
      resources:
        cpu: 1
        memory: 256
      depends_on:
        - vnc
        - nginx-proxy-manager
        - authelia

    vnc:
      name: "VNC Server"
      description: "Remote desktop server with KDE environment"
      image: "ghcr.io/linuxserver/webtop:ubuntu-kde"
      resources:
        cpu: 2
        memory: 2048
      volumes:
        - ./vnc/config:/config
      depends_on:
        - nginx-proxy-manager
        - authelia

    recyclarr:
      name: "Recyclarr"
      description: "Configuration management"
      image: "requestrr/recyclarr:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./recyclarr/config:/config
      depends_on:
        - radarr
        - sonarr

    unpackerr:
      name: "Unpackerr"
      description: "Automated extraction"
      image: "golift/unpackerr:latest"
      resources:
        cpu: 1
        memory: 256
      volumes:
        - ./downloads:/downloads

volumes:
  prometheus_data:
