catalog:
  version: "1.0"
  categories:
    core:
      name: "Core Infrastructure"
      description: "Essential system services"
      services:
        - nginx-proxy-manager
        - authelia
        - redis
        - fail2ban

    media:
      name: "Media Services"
      description: "Media management and streaming"
      services:
        - plex
        - sonarr
        - radarr
        - lidarr
        - bazarr

    downloads:
      name: "Download Management"
      description: "Download clients and indexers"
      services:
        - qbittorrent
        - prowlarr
        - nzbget

    books:
      name: "Book Services"
      description: "Book and audiobook management"
      services:
        - readarr
        - calibre
        - audiobookshelf
        - lazylibrarian

    monitoring:
      name: "Monitoring Services"
      description: "System monitoring and metrics"
      services:
        - prometheus
        - grafana
        - tautulli
        - portainer
        - watchtower

    interface:
      name: "User Interface"
      description: "User-facing dashboards"
      services:
        - organizr
        - overseerr
        - watchlist

  services:
    nginx-proxy-manager:
      name: "Nginx Proxy Manager"
      description: "Reverse proxy and SSL management"
      image: "jc21/nginx-proxy-manager:latest"
      ports:
        - "80:80"
        - "81:81"
        - "443:443"
      volumes:
        - data:/data
        - letsencrypt:/etc/letsencrypt

    authelia:
      name: "Authelia"
      description: "Authentication and SSO provider"
      image: "authelia/authelia:latest"
      volumes:
        - config:/config
      depends_on:
        - redis

    redis:
      name: "Redis"
      description: "Session management and caching"
      image: "redis:latest"
      volumes:
        - data:/data

    fail2ban:
      name: "Fail2Ban"
      description: "Intrusion prevention system"
      image: "crazymax/fail2ban:latest"
      volumes:
        - data:/data
        - logs:/var/log:ro

    plex:
      name: "Plex Media Server"
      description: "Media streaming server"
      image: "lscr.io/linuxserver/plex:latest"
      network_mode: "host"
      volumes:
        - config:/config
        - media:/media

    sonarr:
      name: "Sonarr"
      description: "TV series management"
      image: "lscr.io/linuxserver/sonarr:latest"
      volumes:
        - config:/config
        - media/tv:/tv
        - downloads:/downloads
      depends_on:
        - qbittorrent
        - prowlarr

    radarr:
      name: "Radarr"
      description: "Movie management"
      image: "lscr.io/linuxserver/radarr:latest"
      volumes:
        - config:/config
        - media/movies:/movies
        - downloads:/downloads
      depends_on:
        - qbittorrent
        - prowlarr

    qbittorrent:
      name: "qBittorrent"
      description: "Torrent client"
      image: "ghcr.io/hotio/qbittorrent:latest"
      ports:
        - "8080:8080"
      volumes:
        - config:/config
        - downloads:/downloads

    prowlarr:
      name: "Prowlarr"
      description: "Indexer manager"
      image: "lscr.io/linuxserver/prowlarr:latest"
      volumes:
        - config:/config
      depends_on:
        - qbittorrent

    prometheus:
      name: "Prometheus"
      description: "Metrics collection"
      image: "prom/prometheus:latest"
      volumes:
        - config:/etc/prometheus
        - data:/prometheus

    grafana:
      name: "Grafana"
      description: "Metrics visualization"
      image: "grafana/grafana:latest"
      volumes:
        - data:/var/lib/grafana
      depends_on:
        - prometheus

volumes:
  data:
  config:
  media:
  downloads:
  logs:
