version: '3.8'

networks:
  proxy:
    external: true
  downloads:
    name: downloads
    driver: bridge

volumes:
  qbittorrent_config:
    name: qbittorrent_config
  prowlarr_config:
    name: prowlarr_config
  sabnzbd_config:
    name: sabnzbd_config
  downloads:
    name: downloads
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR:-/opt/media-server/downloads}

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - proxy
      - downloads
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent_config:/config
      - downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy
      - downloads
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    volumes:
      - prowlarr_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 30s
      timeout: 10s
      retries: 3

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - proxy
      - downloads
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    volumes:
      - sabnzbd_config:/config
      - downloads:/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    networks:
      - downloads
    environment:
      - TZ=${TZ}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${VPN_CONFIG:-/opt/media-server/vpn/client.ovpn}:/vpn/client.ovpn:ro
    restart: unless-stopped
    # All download services that need VPN access should use network_mode: "service:vpn"
    # This ensures their traffic goes through the VPN
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "1.1.1.1"]
      interval: 30s
      timeout: 10s
      retries: 3
