# Domain Configuration Example
# This file demonstrates the structure and options for configuring domains

# Primary domain configuration
domain:
  enabled: true
  primaryDomain: "your.domain.com"
  
  # SSL/TLS Configuration
  ssl:
    enabled: true
    provider: "letsencrypt"  # Options: letsencrypt, custom
    email: "admin@your.domain.com"  # Required for Let's Encrypt
    autoRenew: true
    forceSSL: true
    # For custom SSL provider only:
    # cert: "/path/to/certificate.pem"
    # key: "/path/to/private.key"

  # Service-specific subdomains
  subdomains:
    # Media streaming
    - name: "plex"
      service: "plex"
      port: 32400
      ssl: true
      auth: false  # Plex handles its own authentication
    
    # Content management
    - name: "sonarr"
      service: "sonarr"
      port: 8989
      ssl: true
      auth: true
    
    - name: "radarr"
      service: "radarr"
      port: 7878
      ssl: true
      auth: true
    
    - name: "lidarr"
      service: "lidarr"
      port: 8686
      ssl: true
      auth: true
    
    # User interfaces
    - name: "dash"
      service: "dashboard"
      port: 3000
      ssl: true
      auth: true
    
    - name: "request"
      service: "overseerr"
      port: 5055
      ssl: true
      auth: true

  # Dynamic DNS Configuration (optional)
  ddns:
    enabled: false
    provider: "dynu"  # Supported: dynu, cloudflare, duckdns
    username: "your-username"
    password: "your-api-key"
    updateInterval: 300  # seconds
    ipType: "dynamic"  # Options: dynamic, static

# Network security settings
security:
  # Fail2Ban configuration
  fail2ban:
    enabled: true
    findTime: 600
    banTime: 3600
    maxRetry: 5
    
  # Rate limiting
  rateLimit:
    enabled: true
    windowMs: 900000  # 15 minutes
    maxRequests: 100
    
  # CORS settings
  cors:
    enabled: true
    origins:
      - "https://your.domain.com"
      - "https://*.your.domain.com"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"

# Monitoring configuration
monitoring:
  # Health checks
  healthCheck:
    enabled: true
    interval: 30  # seconds
    timeout: 5
    retries: 3
    
  # SSL certificate monitoring
  sslMonitor:
    enabled: true
    expiryWarningDays: 30
    checkInterval: 86400  # 24 hours

# Example service-specific configurations
services:
  # Authentication portal
  authelia:
    enabled: true
    domain: "auth.your.domain.com"
    port: 9091
    
  # Proxy management
  nginx:
    enabled: true
    domain: "proxy.your.domain.com"
    port: 81
    
  # Container management
  portainer:
    enabled: true
    domain: "docker.your.domain.com"
    port: 9000